// Code generated by "stringer -type=EndPoint"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[New-0]
	_ = x[Top-1]
	_ = x[Best-2]
	_ = x[Ask-3]
	_ = x[Show-4]
	_ = x[Jobs-5]
}

const _EndPoint_name = "NewTopBestAskShowJobs"

var _EndPoint_index = [...]uint8{0, 3, 6, 10, 13, 17, 21}

func (i EndPoint) String() string {
	if i < 0 || i >= EndPoint(len(_EndPoint_index)-1) {
		return "EndPoint(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EndPoint_name[_EndPoint_index[i]:_EndPoint_index[i+1]]
}
